### ISSUE TITLE
Exception: NullReferenceException when using .Where(x => x.Field.Contains(txt))

### ISSUE THREAD

**Issue by luca-esse** [zzzprojects/EntityFramework-Classic#20]
The following query throws a NullReferenceException:
`Context.Games.Where(x => x.Name.Contains(searchText)).ToListAsync();`

The problems seems to be the string.Contains() method.

EntityFramework-Classic version: 7.0.24

Here is the stack trace: 

> System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Linq.Expressions.Compiler.LambdaCompiler.EmitMethodCall(Expression obj, MethodInfo method, IArgumentProvider methodCallExpr, CompilationFlags flags)
   at System.Linq.Expressions.Compiler.LambdaCompiler.EmitInvocationExpression(Expression expr, CompilationFlags flags)
   at System.Linq.Expressions.Compiler.LambdaCompiler.EmitExpression(Expression node, CompilationFlags flags)
   at System.Linq.Expressions.Compiler.LambdaCompiler.EmitInstance(Expression instance, Type& type)
   at System.Linq.Expressions.Compiler.LambdaCompiler.EmitMemberExpression(Expression expr)
   at System.Linq.Expressions.Compiler.LambdaCompiler.EmitExpression(Expression node, CompilationFlags flags)
   at System.Linq.Expressions.Compiler.LambdaCompiler.EmitLambdaBody(CompilerScope parent, Boolean inlined, CompilationFlags flags)
   at System.Linq.Expressions.Compiler.LambdaCompiler.EmitLambdaBody()
   at System.Linq.Expressions.Compiler.LambdaCompiler.Compile(LambdaExpression lambda)
   at System.Data.Entity.Core.Objects.ELinq.QueryParameterExpression.EvaluateParameter(Object[] arguments)
   at System.Data.Entity.Core.Objects.ELinq.ELinqQueryState.GetExecutionPlan(Nullable`1 forMergeOption)
   at System.Data.Entity.Core.Objects.ObjectQuery`1.<>c__DisplayClass43_0.<GetResultsAsync>b__1()
   at System.Data.Entity.Core.Objects.ObjectContext.ExecuteInTransactionAsync[T](Func`1 func, IDbExecutionStrategy executionStrategy, Boolean startLocalTransaction, Boolean releaseConnectionOnSuccess, CancellationToken cancellationToken)
   at System.Data.Entity.SqlServer.DefaultSqlExecutionStrategy.ExecuteAsyncImplementation[TResult](Func`1 func)
   at System.Data.Entity.Core.Objects.ObjectQuery`1.GetResultsAsync(Nullable`1 forMergeOption, IDbExecutionStrategy executionStrategy, CancellationToken cancellationToken)
   at System.Data.Entity.Internal.LazyAsyncEnumerator`1.FirstMoveNextAsync(CancellationToken cancellationToken)
   at System.Data.Entity.Infrastructure.IDbAsyncEnumerableExtensions.SingleAsync[TSource](IDbAsyncEnumerable`1 source, CancellationToken cancellationToken)

**Comment by luca-esse** [comment]
Hi Jonathan,
Do you have any update?

Best regards,
Luca

**Comment by JonathanMagnan** [comment]
Hello @luca-esse ,

We passed a lot of time this week on this issue.

We can easily reproduce it, easily find out which line fail.

However, it's currently very hard to find out what's causing it as that happen when a compiled expression is executed.

We continue to investigate it but that one is currently harder to find that we initially though.

**Comment by JonathanMagnan** [comment]
Hello @luca-esse ,

Sorry for being so long, that one is not easy ;(

We finally made a good discovery today about `Expression.Invoke` and `Constant`

The following code work on `.NET Framework` but not on `NET Core`

```csharp
var innerConstant = Expression.Constant("Z");
Expression innerLambda = Expression.Lambda(innerConstant);
var innerConstantLambda = Expression.Constant(innerLambda);
var expression = Expression.Invoke(innerConstantLambda);

var uncompiled = Expression.Lambda(expression);
var compiled = uncompiled.Compile();
```

This code is a more simple version of what is used to perform the `Contains` statement.

I cannot promise anything but I believe we are very close to finding out finally a solution.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @luca-esse ,

The v7.0.29 has been released.

Let me know if everything works as expected.

Best Regards,

Jonathan

**Comment by luca-esse** [comment]
Hello @JonathanMagnan 

Can confirm it's working with the v7.0.29 :)

Best regards,
Luca

**Comment by JonathanMagnan** [comment]
Great ;)
