### ISSUE TITLE
Count() inside string expression in Execute method

### ISSUE THREAD

**Issue by Mat3oo** [zzzprojects/EntityFramework-Classic#59]
I encounter on problem with Count() func inside the Query, while using Execute Extension method of yours.

```cs
_dataStoreService.GetAllElements().Execute<object>("Where(p => (p.Name== "test"))" +
                ".Where(p => p.Active)" +
                ".Where(p => new List<int>() { 1, 2, 3 }.Contains(p.Id))" +
                ".GroupBy(p => new { p.Id, p.Name})" +
                ".Select(p => new { p.Key.Id, p.Key.Name, Counts =  p.Count() }).ToList()")
```

Exception Details:
- Message:
```
Processing of the LINQ expression '(GroupByShaperExpression:
KeySelector: new <>f__AnonymousType0<int, string>(
    Id = (s.Id), 
    Name= (s.Name)
), 
ElementSelector:new ElementDTO{ 
    Id = (ProjectionBindingExpression: Id), 
    Value = (ProjectionBindingExpression: Value), 
    Active = (ProjectionBindingExpression: Active), 
    Code = (ProjectionBindingExpression: Code), 
    Name = (ProjectionBindingExpression: Name) 
}
)' by 'RelationalProjectionBindingExpressionVisitor' failed. This may indicate either a bug or a limitation in EF Core. See https://go.microsoft.com/fwlink/?linkid=2101433 for more detailed information.
```

- Stack trace is:
```
at Microsoft.EntityFrameworkCore.Query.Internal.RelationalProjectionBindingExpressionVisitor.VisitExtension(Expression extensionExpression)
   at System.Linq.Expressions.Expression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.Internal.RelationalProjectionBindingExpressionVisitor.Visit(Expression expression)
   at System.Linq.Expressions.ExpressionVisitor.VisitUnary(UnaryExpression node)
   at System.Linq.Expressions.UnaryExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.Internal.RelationalProjectionBindingExpressionVisitor.Visit(Expression expression)
   at System.Dynamic.Utils.ExpressionVisitorUtils.VisitArguments(ExpressionVisitor visitor, IArgumentProvider nodes)
   at System.Linq.Expressions.ExpressionVisitor.VisitMethodCall(MethodCallExpression node)
   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.Internal.RelationalProjectionBindingExpressionVisitor.Visit(Expression expression)
   at Microsoft.EntityFrameworkCore.Query.Internal.RelationalProjectionBindingExpressionVisitor.VisitNew(NewExpression newExpression)
   at System.Linq.Expressions.NewExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.Internal.RelationalProjectionBindingExpressionVisitor.Visit(Expression expression)
   at Microsoft.EntityFrameworkCore.Query.Internal.RelationalProjectionBindingExpressionVisitor.Translate(SelectExpression selectExpression, Expression expression)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryableMethodTranslatingExpressionVisitor.TranslateSelect(ShapedQueryExpression source, LambdaExpression selector)
   at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.QueryCompilationContext.CreateQueryExecutor[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Storage.Database.CompileQuery[TResult](Expression query, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[TResult](IDatabase database, Expression query, IModel model, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass9_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQueryCore[TFunc](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.Execute[TResult](Expression expression)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1.GetEnumerator()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Z.Expressions.EvalLinq.Execute(String code, Boolean isQueryable, Expression exp, Object[] parameters)
   at System.Linq.QueryableDynamic.Execute[TValue](IQueryable source, String expression, Object parameter)
   at System.Linq.QueryableDynamic.Execute[TValue](IQueryable source, String expression)
   at WebAPI.Controllers.ElementController.ZZZEntityFrameworkClassic(ZZZTransfer query) in *Path removed by me*\WebAPI\Controllers\ElementsController.cs:line 36
   at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<<InvokeActionMethodAsync>g__Logged|12_1>d.MoveNext()
```

**Comment by JonathanMagnan** [comment]
Hello @Mat3oo ,

Is this query working without our library? So purely with LINQ? It looks more like some limitations about how the expression is handled in Entity Framework.

If you think I'm wrong, do you think you could provide a runnable project with this issue? It will help my developer to make sure he debug the same issue as you instead of creating a new model that might be different than yours.

Best Regards,

Jon

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)

**Comment by Mat3oo** [comment]
> Is this query working without our library? So purely with LINQ? It looks more like some limitations about how the expression is handled in Entity Framework.

Yes, it's working with pure LINQ
> If you think I'm wrong, do you think you could provide a runnable project with this issue? It will help my developer to make sure he debug the same issue as you instead of creating a new model that might be different than yours.

Here is [repo](https://github.com/Mat3oo/EntityFramework-Classic_Count_example) (master branch) with replicated my issue.

**Comment by JonathanMagnan** [comment]
Thank you for the project @Mat3oo ,

We will look at it.

I better understand your last issue as well now.

Btw, is there a reason why you use `EF Classic` when you don't use it?

It looks more like you want to use the following library: https://eval-expression.net/ (which is referenced by EF Classic)

**Comment by JonathanMagnan** [comment]
Mat3oo, happy to hear your issue is resolved, 

Let me know if you have any questions. 

Best regards, 

Jon
