### ISSUE TITLE
EDMX - Unable to cast object of type ObjectQuery to DbQuery in .Include()

### ISSUE THREAD

**Issue by WojciechNagorski** [zzzprojects/EntityFramework-Classic#66]
Many thanks for your work on the amazing Z.EntityFramework.Plus and Z.EntityFramework.Classic.

Currently I'm using EDMX and EntityFramework 6.4.4 with Z.EntityFramework.Plus.EF6 and everything works great. 

Currently I have to migrate my project to new .NET 7 and I have to do this incrementally. In first step I want to compile my project to .NET Standard 2.0, so I need to use Z.EntityFramework.Classic. I changed the nugets, my project compiles fine, but I got exception at runtime.

```
System.InvalidCastException: Unable to cast object of type 'System.Data.Entity.Core.Objects.ObjectQuery`1[DatabaseAPI.User]' to type 'System.Data.Entity.Infrastructure.DbQuery`1[DatabaseAPI.User]'.
   at EntityFrameworkClassicExtensions.AsDbQuery[TQuery](IQueryable`1 this)
   at System.Data.Entity.QueryableExtensions.Include[TResult,TProperty](IQueryable`1 source, Expression`1 path)
   at CommandCenter.Repositories.UsersRepository.GetQueryable() in C:\code\CommandCenter\CommandCenterInfrastructure\CommandCenter.Repositories\UsersRepository.cs:line 83
   at CommandCenter.Repositories.GenericRepository`2.Get(Expression`1 predicate) in C:\code\CommandCenter\CommandCenterInfrastructure\CommandCenter.Repositories\GenericRepository.cs:line 91
   at CommandCenter.Services.UsersProvider.Get(String login, Boolean ignoreCase) in C:\code\CommandCenter\CommandCenterDomain\CommandCenter.Services\UsersProvider.cs:line 93
   at WebAPI.Filters.Validators.Utils.HttpRequestSignatureValidator.Validate(HttpRequestMessage request) in C:\code\CommandCenter\WebAPI\Filters\Validators\Utils\HttpRequestSignatureValidator.cs:line 99
   at WebAPI.Filters.Validators.ApiUserAuthorizeAttribute.DoesValidRequestSignatureExist(HttpActionContext context) in C:\code\CommandCenter\WebAPI\Filters\Validators\ApiUserAuthorizeAttribute.cs:line 109
   at WebAPI.Filters.Validators.ApiUserAuthorizeAttribute.CustomOnAuthorization(HttpActionContext context) in C:\code\CommandCenter\WebAPI\Filters\Validators\ApiUserAuthorizeAttribute.cs:line 84
   at WebAPI.Filters.Validators.CustomAuthorizeAttribute.OnAuthorization(HttpActionContext context) in C:\code\CommandCenter\WebAPI\Filters\Validators\CustomAuthorizeAttribute.cs:line 58
   at System.Web.Http.Filters.AuthorizationFilterAttribute.OnAuthorizationAsync(HttpActionContext actionContext, CancellationToken cancellationToken)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.AuthorizationFilterAttribute.<ExecuteAuthorizationFilterAsyncCore>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.AuthorizationFilterAttribute.<ExecuteAuthorizationFilterAsyncCore>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.AuthorizationFilterAttribute.<ExecuteAuthorizationFilterAsyncCore>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__15.MoveNext()
```

I'm using EDMX that generates my `MyEntities` context:
```
public partial class MyEntities : ObjectContext
{
        public ObjectSet<User> Users
        {
            get
            {
                if ((_Users == null))
                {
                    _Users = base.CreateObjectSet<User>("Users");
                }
                return _Users;
            }
        }
        private ObjectSet<User> _Users;

/// Other collections ...
}
```

Then I get data with Include() method:
```
public override IQueryable<User> GetQueryable()
{
    return this.Entities.Users.AsQueryable()
        .Include(i => i.UserPrivileges)
        .Include(i => i.UserEmails)
        .Include(i => i.UserSetting);
}
```

I've used DotPeek because I wanted to understand this problem and I saw the following implementation:
```
  public static class QueryableExtensions
  {
....
    public static IIncludeDbQuery<TResult, TProperty> Include<TResult, TProperty>(
      this IQueryable<TResult> source,
      Expression<System.Func<TResult, TProperty>> path)
    {
      Check.NotNull<Expression<System.Func<TResult, TProperty>>>(path, nameof (path));
      string path1;
      if (!DbHelpers.TryParsePath(path.Body, out path1) || path1 == null)
        throw new ArgumentException(System.Data.Entity.Resources.Strings.DbExtensions_InvalidIncludePathExpression, nameof (path));
      return (IIncludeDbQuery<TResult, TProperty>) new IncludeDbQuery<TResult, TProperty>(source.Include<TResult>(path1).AsDbQuery<TResult>(), path1);
    }
...
```
The `Include()` method returns even different type. It should returns `IQuerable<T>` but it returns `IIncludeDbQuery<TResult, TProperty>` and that requires a lot of code changes after changing the library.

Then I've checked the code on master, and it looks different:

https://github.com/zzzprojects/EntityFramework-Classic/blob/4953e0478771ec1b065503a12a8bbef132569492/src/Shared/EntityFramework/QueryableExtensions.cs#L578-L592

I don't know why but it takes code from:

https://github.com/zzzprojects/EntityFramework-Classic/blob/4953e0478771ec1b065503a12a8bbef132569492/src/Shared/EntityFramework.Community.Shared/Include/IncludeDbQuery%602.cs#L38-L47

I've checked the latest version of library [7.2.5](https://www.nuget.org/packages/Z.EntityFramework.Classic/7.2.5) and [7.2.4](https://www.nuget.org/packages/Z.EntityFramework.Classic/7.2.4)

The same exception was created https://github.com/zzzprojects/EntityFramework-Classic/issues/53 but user close this issue because he move back to EF + EF.Plus.

**Comment by WojciechNagorski** [comment]
There is a mini reproduction: 
[EdmxTest.zip](https://github.com/zzzprojects/EntityFramework-Classic/files/12161488/EdmxTest.zip)

![image](https://github.com/zzzprojects/EntityFramework-Classic/assets/17333903/be4febc2-ba3b-443a-8dde-54829c8f1672)
* EdmxTest - Tests with EF 6 - worsk
* EdmxTestClassic - Tests with Z.EntityFramework.Classic - does not work

**Comment by WojciechNagorski** [comment]
The problem occurred because I use `ObjectContext` as a base class instead of `DbContext`. And `ObjectSet<>` Instead of `DbSet`.

**Comment by JonathanMagnan** [comment]
Hello @WojciechNagorski ,

Thank you for reporting and your project.

My developer will look at it soon.

Best Regards,

Jon

**Comment by JonathanMagnan** [comment]
Hello @WojciechNagorski ,

Look like your project still use the old `ObjectContext` instead of inheriting of a `DbContext`.

In this case, some method of our library will requires to use the `GetOrCreateDbContext` method from our `Z.EntityFramework.Extensions.Classic` library (already included in EF Classic).

```csharp
var result = context.GetOrCreateDbContext().Set<Users>().Include(p => p.Project).ToList();
```

It will transform your `ObjectContext` into a `DbContext` and from it, everything should now work as expected.

Let me know if that solution could work for you.

Best Regards,

Jon

**Comment by WojciechNagorski** [comment]
DbContext is a wrapper of ObjectContext and ObjectContext have different features. It is not old, but not default. EF supports both of them and I think Z.EntityFramework.Classic should support too. I have a huge project and this will be painful for me.

**Comment by WojciechNagorski** [comment]
Z.EntityFramework.Plus.Ef6 supports ObjectContext very well.

**Comment by WojciechNagorski** [comment]
I think it should be similar to this implementation:
https://github.com/zzzprojects/EntityFramework-Classic/blob/4953e0478771ec1b065503a12a8bbef132569492/src/Shared/EntityFramework/QueryableExtensions.cs#L464-L474

**Comment by WojciechNagorski** [comment]
EF Classic should be fully compatible with normal EF. Otherwise, what it doesn't support should be added to the Readme.md.

**Comment by WojciechNagorski** [comment]
@JonathanMagnan Any updates?

**Comment by JonathanMagnan** [comment]
Hello @WojciechNagorski ,

The fix we started was refused 2 weeks ago. Since then, we didn't have any idea how to fix it 2 major errors we had.

On the good side, time did the work, and when I saw your message, the idea about how to fix it comes as well.

So a new branch is currently under review. I cannot guarantee anything but I currently have high hope that this one will be accepted.

I will give you an update when I will have one.

Best Regards,

Jon

**Comment by JonathanMagnan** [comment]
Hello @WojciechNagorski ,

Just to let you know that the fix has been accepted.

The fix should be released with our monthly release on 2023-09-12

**Comment by JonathanMagnan** [comment]
Hello @WojciechNagorski ,

The v7.2.7 has been finally released.

Let us know if everything is now working as expected with the `Include` method for the `ObjectContext.

Best Regards,

Jon

**Comment by WojciechNagorski** [comment]
I have a large project and now I get another exception:
```
System.Data.Entity.Core.MetadataException: Unable to load the specified metadata resource.
   at System.Data.Entity.Core.Metadata.Edm.MetadataArtifactLoaderCompositeResource.LoadResources(String assemblyName, String resourceName, ICollection`1 uriRegistry, MetadataArtifactAssemblyResolver resolver)
   at System.Data.Entity.Core.Metadata.Edm.MetadataArtifactLoaderCompositeResource.CreateResourceLoader(String path, ExtensionCheck extensionCheck, String validExtension, ICollection`1 uriRegistry, MetadataArtifactAssemblyResolver resolver)
   at System.Data.Entity.Core.Metadata.Edm.MetadataCache.SplitPaths(String paths)
   at System.Data.Entity.Core.Common.Utils.Memoizer`2.Result.GetValue()
   at System.Data.Entity.Core.Common.Utils.Memoizer`2.Evaluate(TArg arg)
   at System.Data.Entity.Core.Metadata.Edm.MetadataCache.GetArtifactLoader(DbConnectionOptions effectiveConnectionOptions)
   at System.Data.Entity.Core.Metadata.Edm.MetadataCache.GetMetadataWorkspace(DbConnectionOptions effectiveConnectionOptions)
   at System.Data.Entity.Core.EntityClient.EntityConnection.GetMetadataWorkspace()
   at System.Data.Entity.Core.Objects.ObjectContext..ctor(EntityConnection connection, Boolean isConnectionConstructor, ObjectQueryExecutionPlanFactory objectQueryExecutionPlanFactory, Translator translator, ColumnMapFactory columnMapFactory)
   at System.Data.Entity.Core.Objects.ObjectContext..ctor(String connectionString, String defaultContainerName)
   at DatabaseAPI.ContextEntities..ctor() in D:\work\Project\Database\DatabaseModel\DatabaseModelPartials.cs:line 81
   at DatabaseService.DatabaseService.<>c.<.ctor>b__5_0() in D:\work\Project\Database\DatabaseService\DatabaseService.cs:line 133
   at DatabaseService.DatabaseService.GetAllProjects() in D:\work\Project\Database\DatabaseService\DatabaseService.cs:line 442
```

**Comment by WojciechNagorski** [comment]
And my mini repro [EdmxTest.zip](https://github.com/zzzprojects/EntityFramework-Classic/files/12161488/EdmxTest.zip) does not work after updating `Z.EntityFramework.Classic` to `7.2.7`

**Comment by JonathanMagnan** [comment]
Hello @WojciechNagorski ,

Could you do a `Clean Solution` and try it again?

The current repo still use `7.2.5`, when upgrading to `7.2.7` and making sure that the newest dll is used by cleaning the solution, we cannot reproduce anymore the problem.

Let make sure this one work before working your larger solution problem.

Best Regards,

Jon

**Comment by WojciechNagorski** [comment]
@JonathanMagnan You are right. I've `Clean Solution` and mini repro works. 

I'm going to close this issue. My large application still does not work, but I need more time to test everything. I will start a new issue if the problem persists.
