### ISSUE TITLE
Exception: 'Stream not found.' when using UpdateFromQueryAsync

### ISSUE THREAD

**Issue by neoGeneva** [zzzprojects/EntityFramework-Classic#7]
Here's the stacktrace:

```
   at .(DbContext this, String )
   at .(DbContext this, List`1 , String )
   at .(DbContext )
   at .(DbContext )
   at .(DbContext this)
   at DbContextExtensions.UpdateFromQuery[TEntity](IQueryable`1 query, Expression`1 updateExpression, Action`1 bulkOperationFactory)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
--- End of stack trace from previous location where exception was thrown ---
   at DbContextExtensions.UpdateFromQueryAsync[TEntity](IQueryable`1 query, Expression`1 updateExpression)
```

It's hard to tell exactly what's going on, but at a guess it looks like something is trying to read the csdl, ssdl and msl, but not loading it from the in memory resources generated by `EntityFrameworkManager.UseDatabaseFirst()`

Sorry if this isn't the correct repo for this issue, I wasn't sure where to log issues for Z.EntityFramework.Extensions.Classic

Version: 
* Z.EntityFramework.Classic 7.0.12
* Z.EntityFramework.Extensions.Classic 3.15.19

OS: Windows 10
TargetFramework: netcoreapp2.1

**Comment by JonathanMagnan** [comment]
Hello @neoGeneva ,

Just to let you know that this issue has been fixed but we prefer to make a few more tests before releasing it.  A new version should be available before Monday.

Thank you for your good word ;)

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @neoGeneva ,

The v7.0.14 has been released.

We should now read the resource that has been generated by the `UseDatabaseFirst` method instead of trying to retrieve them (the logic used in the `.NET Framework`)

Let me know if everything is working as expected.

Best Regards,

Jonathan

**Comment by neoGeneva** [comment]
Looks like it's working as expected now, thanks!
